spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret:  ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google
          naver:
            client-id:  ${NAVER_CLIENT_ID}
            client-secret:  ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email
  profiles:
    include: config
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: -1 #무제한
      max-request-size: -1 #무제한

  data:
    redis:
      host: stay-with-me-dangsan-cluster-001.axlnad.0001.apn2.cache.amazonaws.com
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 500ms

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: stay.with.me.api.model.dto
  type-handlers-package: stay.with.me.spring.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: INFO
    org.apache.ibatis: INFO
    org.springframework.web: INFO
  file:
    name: app.log
    path: /apps/stay-with-me

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

#server:
#  tomcat:
#    threads:
#      max: 50

server:
  tomcat:
    threads:
      max: 50
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        same-site: none
        secure: true

