spring:
  profiles:
    include: config
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: -1 #무제한
      max-request-size: -1 #무제한

  data:
    redis:
      host: stay-with-me-dangsan-cluster-001.axlnad.0001.apn2.cache.amazonaws.com
      port: 6379

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: stay.with.me.api.house.model.dto
  type-handlers-package: stay.with.me.spring.config.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false